### ISSUE TITLE
关于“Background”这个单词的中文译文，各位汉化者有什么建议？

### ISSUE THREAD

**Issue by yimengqinyao** [Maximoff/MPatcher-translations#7]
This issue is for Chinese translators to discuss, and I hope that the repository owner "Maximoff" will not close this issue for the time being. Thank you!

请各位来到这里进行汉化的国人或会中文的外国友人，给这个单词提供一个更好的翻译用于以下两种情况中（不确定还有没有别的情况，我暂时只发现以下两处）。

第一处是在删除、移动、拷贝等文件操作时出现的进程消息框的左下角（如下图），没发现第二处之前，我翻译成“置于后台”，那么它也符合将消息框放至后台运行的意思。点击后，消息框也确实消失了，之后在下拉通知栏中就会有一条通知消息。
![Screenshot_2024-05-31-20-58-02-105_ru maximoff apktool-edit](https://github.com/Maximoff/MPatcher-translations/assets/148033871/8532f10f-f672-467c-a933-be28a44bce00)

但现在我又发现它还会出现在查看XML格式的图片时的预览框左下角（如下图），点击后，却不是将预览框放至后台，而是改变预览框中图片的背景颜色，那么用之前的那个翻译就不合适了。
![Screenshot_2024-05-31-20-57-38-455_ru maximoff apktool](https://github.com/Maximoff/MPatcher-translations/assets/148033871/c3f6c8cd-2de7-42d0-803d-b282c69d1a16)

作者Maximoff大神，居然在两处不同的场景中共用这一个单词，搞得我都不知道该如何汉化了。
不知在座的各位大神，有没有更符合用于这两种情况的的中文意思？若有，请提供给我，或直接在本仓库里面提交新的译文。谢谢各位了！

**Comment by Maximoff** [comment]
I can just add another line for this if that makes it easier for you. I should have said this earlier. There's nothing to discuss here

**Comment by yimengqinyao** [comment]
> I can just add another line for this if that makes it easier for you. I should have said this earlier. There's nothing to discuss here

Sorry, this was supposed to be sent to Apktool-M-translations, but it turned out to be in the wrong place.

**Comment by Maximoff** [comment]
> > I can just add another line for this if that makes it easier for you. I should have said this earlier. There's nothing to discuss here
> 
> Sorry, this was supposed to be sent to Apktool-M-translations, but it turned out to be in the wrong place.

It's okay, I understood from the screenshots what it was about. I added a separate line for the preview background, you can fix it.
